[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_18']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader --no-interaction',
    'npm ci --silent'
]

[phases.build]
cmds = [
    'npm run build',
    'php artisan config:cache --no-interaction',
    'php artisan route:cache --no-interaction',
    'php artisan view:cache --no-interaction'
]

[start]
cmd = 'bash start.sh'