[build]
  builder = "docker"
  buildCommand = "docker build -t military-fleet-management ."
  startCommand = "docker run -p ${PORT}:80 -e APP_ENV=production -e APP_DEBUG=false -e APP_KEY=${base64:gBdGwq8aXoo6HBKE+8lE/ssJPImJFIz8JcZM4/jsjHc=} military-fleet-management"

[deploy]
  startTimeout = 600
  healthcheckPath = "/"
  healthcheckTimeout = 100
  restartDelay = 5
