[build]
  builder = "docker"
  buildCommand = "docker build -t military-fleet-management ."
  startCommand = "docker run -p ${PORT}:8000 military-fleet-management"

[deploy]
  startTimeout = 600
  healthcheckPath = "/"
  healthcheckTimeout = 100
  restartDelay = 5
