services:
  - type: web
    name: carsmanagement
    env: docker
    dockerfilePath: ./Dockerfile.render
    plan: free
    region: frankfurt
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:XuvyCgMJdH6yEMmGtIyilBSF3mdjq2RE4kgrw9j1BL0=
      - key: APP_URL
        value: https://carsmanagement.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /app/database/database.sqlite
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: MAIL_MAILER
        value: log
      - key: APP_LOCALE
        value: fr
      - key: APP_FALLBACK_LOCALE
        value: en